def create_file():
    with open("Easy.txt", "w", encoding="utf-8") as f:
        f.write("wyraz:język polski\nmama:relacje\ntata:relacje\nsiostra:relacje\nsyn:relacje\ncórka:relacje\n"
                "ziomek:relacje\nbrak:relacje\nwnuk:relacje\nwnuczka:relacje\nniedźwiedź:zwierzęta\nsłoń:zwierzęta\n"
                "wiewiórka:zwierzęta\nkomputer:technika\nklawiatura:technika\nkoleżanka:relacje\nkawa:pożywienie\n"
                "herbata:pożywienie\nsok:pożywienie\nmonitor:technika\nmazak:artykuły biurowe\nmyszka:technika\n"
                "mysz:zwierzęta\nguzik:technika\nkabel:technika\nkalkulator:technika\nchusteczka:higiena\n"
                "gumka:artykuły biurowe\nkomórka:technika\nkoszyk:przechowanie\ntorebka:moda\n"
                "długopis:artykuły biurowe\nnabój:broń\npistolet:broń\nkarabin:broń\nkuweta:dom i ogród\n"
                "pies:zwierzęta\nkalendarz:organizacja\ndrzwi:dom i ogród\nstół:dom i ogród\nkrzesło:dom i ogród\n"
                "tapczan:dom i ogród\nłóżko:dom i ogród\nszafa:dom i ogród\npodłoga:dom i ogród\npółka:dom i ogród\n"
                "wtyczka:technika\ndrukarka:technika\nściana:dom i ogród\npiłka:sport i zabawa\nokno:dom i ogród\n"
                "system:informatyka\nzlew:dom i ogród\nwoda:natura\nziemia:natura\nkaloryfer:dom i ogród\n"
                "dziurkacz:artykuły biurowe\npaczka:zakupy\nsamochód:środki lokomocji\nskuter:środki lokomocji\n"
                "motocykl:środki lokomocji\nmotor:środki lokomocji\nsilnik:technika\nkoło:geometria\n"
                "hulajnoga:środki lokomocji\nzasłonka:dom i ogród\nfiranka:dom i ogród\nbuty:moda\nkozaki:moda\n"
                "sandały:moda\nmiecz:broń\nszabla:broń\ndzida:broń\nhalabarda:broń\nstrzała:broń\nkusza:broń\n"
                "brzuch:człowiek\ngłowa:człowiek\nwisielec:człowiek\nkartka:artykuły biurowe\npapier:artykuły biurowe\n"
                "radio:technika\nkaseta:technika\npłyta:technika\ndach:budownictwo\nklamka:dom i ogród\n"
                "sedes:dom i ogród\nprysznic:dom i ogród\nwanna:dom i ogród\nsklep:budownictwo\nkasa:zakupy\n"
                "pieniądze:zakupy\nwaluta:zakupy\ndrzewa:natura\ntrawa:natura\nkwiat:natura\nskała:natura\n"
                "góra:natura\npociąg:środki lokomocji\nlokomotywa:środki lokomocji\nwagon:środki lokomocji\n"
                "linie:geometria\nkwadrat:geometria\nnapięcie:technika\nkurz:dom i ogród\nkolega:relacje\n"
                "pracownik:zawód\nniebo:natura\nsłońce:kosmos\ngwiazda:kosmos\nkosmos:kosmos\nplaneta:kosmos\n"
                "księżyc:kosmos\ndzień:czas\nranek:czas\npolana:natura\njezioro:natura\nmorze:natura\nocean:natura\n"
                "wyżyna:natura\nkałuża:pogoda\ndeszcz:pogoda\nogień:natura\nprąd:technika\ngrzmot:pogoda\n"
                "piorun:pogoda\nkrasnolud:fantastyka\nczłowiek:człowiek\nniziołek:fantastyka\nstopa:człowiek\n"
                "gałąź:natura\nliście:natura\nparking:przemieszczanie\nbudynek:budownictwo\nasfalt::budownictwo\n"
                "chodnik:przemieszczanie\npodjazd:przemieszczanie\nbutelka:przechowanie\nśniadanie:pożywienie\n"
                "obiad:pożywienie\nkurczak:zwierzęta\nkrowa:zwierzęta\nświnia:zwierzęta\nkolacja:pożywienie\n"
                "podwieczorek:pożywienie\nżona:relacje\nmąż:relacje\npowietrze:natura\ntlen:chemia\n"
                "balon:sport i zabawa\nblok:budownictwo\nmieszkanie:budownictwo\ngaraż:budownictwo\n"
                "pojazd:środki lokomocji\nlatarnia:technika\nżyrandol:dom i ogród\nwłącznik:dom i ogród\n"
                "kula:geometria\nstożek:geometria\ntulipan:natura\nziemniak:pożywienie\ngruszka:pożywienie\n"
                "jabłko:pożywienie\nwinogrono:pożywienie\norzech:pożywienie\ntruskawka:pożywienie\n"
                "doniczka:dom i ogród\nżarówka:dom i ogród\ndeska:budownictwo\ngłośnik:technika\ntelewizor:technika\n"
                "pączek:pożywienie\nchleb:pożywienie\nmakaron:pożywienie\npark:natura\nsiłownia:budownictwo\n"
                "maszyna:technika\nbarometr:technika\npiwo:pożywienie\nalkohol:pożywienie\npaliwo:środki lokomocji\n"
                "peron:budownictwo\nstacja:budownictwo\nautobus:środki lokomocji\ndworzec:budownictwo\n"
                "dwór:budownictwo\npałac:budownictwo\nzamek:budownictwo\nksiężniczka:zawód\nkościół:budownictwo\n"
                "ksiądz:zawód\nspodnie:moda\nskarpeta:moda\nucho:człowiek\nusta:człowiek\nmózg:człowiek\n"
                "palec:człowiek\nsosna:natura\nkura:zwierzęta\nindyk:zwierzęta\ntydzień:czas\nmiesiąc:czas\n"
                "godzina:czas\nminuta:czas\nlustro:dom i ogród\nmuzyka:muzyka\npięść:człowiek")
